# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCompra():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_compra(self):
    self.driver.get("https://enjoytravell.com/")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) .btn").click()
    self.driver.find_element(By.NAME, "nombre_cliente").click()
    self.driver.find_element(By.NAME, "nombre_cliente").send_keys("William Alexander Quintero Neira")
    self.driver.find_element(By.NAME, "pais_cliente").click()
    self.driver.find_element(By.NAME, "pais_cliente").send_keys("Colombia")
    self.driver.find_element(By.NAME, "nro_personas").click()
    self.driver.find_element(By.NAME, "nro_personas").send_keys("5")
    self.driver.find_element(By.NAME, "fecha_llegada").click()
    self.driver.find_element(By.NAME, "fecha_llegada").click()
    self.driver.find_element(By.NAME, "fecha_llegada").send_keys("2023-02-25")
    self.driver.find_element(By.NAME, "numero_wasap").click()
    self.driver.find_element(By.NAME, "numero_wasap").click()
    self.driver.find_element(By.NAME, "numero_wasap").send_keys("3102004474")
    self.driver.find_element(By.NAME, "correo ").click()
    self.driver.find_element(By.NAME, "correo ").send_keys("wialqune@gmail.com")
    self.driver.find_element(By.ID, "lista_personas").click()
    self.driver.find_element(By.ID, "lista_personas").send_keys("Validacion de pruebas para pasar a la empresa")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
